### ISSUE TITLE
This plugin needs some love

### ISSUE THREAD

**Issue by laughedelic** [alexarchambault/sbt-ammonite#1]
Hi! I'd like to use this plugin, but it looks kind of abandoned. I tried to add to my `~/.sbt/0.13/plugins/plugins.sbt`

``` scala
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("com.github.alexarchambault" %% "sbt-ammonite" % "0.1.0-SNAPSHOT")
```

and then to `~/.sbt/0.13/global.sbt`:

``` scala
ammonite.AmmonitePlugin.autoImport.ammoniteVersion := "0.4.4"
```

auto-import doesn't work for some reason.

Then the plugin loads and resolves ammonite-0.4.4, but nothing works in it:

```
Welcome to the Ammonite Repl 0.4.4
(Scala version 2.11.7 Java 1.8.0_25)
@ help
stty: standard input: unable to perform all requested operations
[error] (run-main-0) java.lang.RuntimeException: Nonzero exit value: 1
java.lang.RuntimeException: Nonzero exit value: 1
    at scala.sys.package$.error(package.scala:27)
    at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
    at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
    at ammonite.terminal.TTY$.stty(Utils.scala:97)
    at ammonite.terminal.TermCore$.readLine(TermCore.scala:220)
    at ammonite.repl.frontend.FrontEnd$Ammonite$.readLine(FrontEnd.scala:148)
    at ammonite.repl.frontend.FrontEnd$Ammonite$.action(FrontEnd.scala:63)
    at ammonite.repl.Repl.action(Repl.scala:45)
    at ammonite.repl.Repl.loop$1(Repl.scala:83)
    at ammonite.repl.Repl.run(Repl.scala:97)
    at ammonite.repl.Repl$.run(Repl.scala:161)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:145)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:145)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.repl.Repl$.main(Repl.scala:145)
    at ammonite.repl.Repl.main(Repl.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
[trace] Stack trace suppressed: run last ammonite:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last ammonite:runMain for the full output.
[error] (ammonite:runMain) Nonzero exit code: 1
[error] Total time: 17 s, completed Aug 18, 2015 1:12:52 PM
```

**Comment by alexarchambault** [comment]
I don't know the exact reason of why it stopped working as is. I just changed a bit the internals of the plugin though, and it works better now. Test it with the development version. Note that the command to launch Ammonite changed to `ammonite:run`.
