### ISSUE TITLE
New versions of Ammonite don't work.

### ISSUE THREAD

**Issue by gorzell** [alexarchambault/sbt-ammonite#16]
There were changes the to package that the Main class lives in (`ammonite.Main().run()`) and the latest version simply don't work.
```
$ ammonite:run
[info] Updating {file:/Users/gorzell/dev/git/keen/devops/deployment-service/}root...
[info] Resolving org.ow2.asm#asm-util;4.1 ...
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/ammonite-repl_2.11.11/0.8.4/ammonite-repl_2.11.11-0.8.4.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#ammonite-repl_2.11.11;0.8.4!ammonite-repl_2.11.11.jar (362ms)
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/ammonite-terminal_2.11/0.8.4/ammonite-terminal_2.11-0.8.4.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#ammonite-terminal_2.11;0.8.4!ammonite-terminal_2.11.jar (180ms)
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/ammonite-util_2.11.11/0.8.4/ammonite-util_2.11.11-0.8.4.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#ammonite-util_2.11.11;0.8.4!ammonite-util_2.11.11.jar (188ms)
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/ammonite-runtime_2.11.11/0.8.4/ammonite-runtime_2.11.11-0.8.4.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#ammonite-runtime_2.11.11;0.8.4!ammonite-runtime_2.11.11.jar (258ms)
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/ammonite-compiler_2.11.11/0.8.4/ammonite-compiler_2.11.11-0.8.4.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#ammonite-compiler_2.11.11;0.8.4!ammonite-compiler_2.11.11.jar (332ms)
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/ammonite-ops_2.11/0.8.4/ammonite-ops_2.11-0.8.4.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#ammonite-ops_2.11;0.8.4!ammonite-ops_2.11.jar (154ms)
[info] Done updating.
[info] Running ammonite.repl.Main
[error] (run-main-0) java.lang.ClassNotFoundException: ammonite.repl.Main
java.lang.ClassNotFoundException: ammonite.repl.Main
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[trace] Stack trace suppressed: run last ammonite:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
```

I would also be nice to make the default something more current and allow people to set the `ammoniteVersion` from within their build file.

**Comment by simlei** [comment]
this also occurs for me.

trace:
[error] (run-main-0) java.lang.ClassNotFoundException: ammonite.repl.Main
java.lang.ClassNotFoundException: ammonite.repl.Main
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sbt.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:59)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sbt.Run.getMainMethod(Run.scala:72)
        at sbt.Run.run0(Run.scala:60)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:748)
[debug]         Thread run-main-0 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:2128)
        at sbt.package$.toError(package.scala:4)
        at ammonite.AmmonitePlugin$$anonfun$runTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(AmmonitePlugin.scala:40)
        at ammonite.AmmonitePlugin$$anonfun$runTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(AmmonitePlugin.scala:36)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[error] (myapp/ammonite:run) Nonzero exit code: 1

**Comment by simlei** [comment]
I tried ammonite versions down until v0.8.3, lower than which ivy wasn't able to resolve the package anymore. None worked. I never actually had this plugin working before, so I cannot be sure I don't have an unrelated configuration issue...

**Comment by LPTK** [comment]
Same problem here. I can't use this plugin anymore!
