### ISSUE TITLE
Need to update for Ammonite 0.4.7, 0.4.6 gone from repos

### ISSUE THREAD

**Issue by jbweeks** [alexarchambault/sbt-ammonite#4]
Looks like 0.4.6 has been pulled from the repos, for some reason:

:: problems summary ::
:::: WARNINGS
        module not found: com.lihaoyi#ammonite-shell_2.11;0.4.6

```
==== central: tried

  http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.11/0.4.6/ammonite-shell_2.11-0.4.6.pom

  -- artifact com.lihaoyi#ammonite-shell_2.11;0.4.6!ammonite-shell_2.11.jar:

  http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.11/0.4.6/ammonite-shell_2.11-0.4.6.jar
```

**Comment by alexarchambault** [comment]
Couldn't there be anything particular with your `build.sbt`, like it trying to pull another version of Ammonite, or anything else? No `ammonite-shell` 0.4.6 can be found because... this module didn't exist at the time! It only appeared in Ammonite 0.4.7.  I don't really know how it can end up being pulled in version 0.4.6 here.

(Sorry for the late answer, hope you found a way to address this problem before :-| ).

**Comment by chernetsov** [comment]
hmm... seems I got the same thing here

```
:: resolving dependencies :: com.lihaoyi#ammonite-shell_2.11-caller;working
    confs: [default]

:: problems summary ::
:::: WARNINGS
        module not found: com.lihaoyi#ammonite-shell_2.11;0.4.6

    ==== central: tried

      http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.11/0.4.6/ammonite-shell_2.11-0.4.6.pom

      -- artifact com.lihaoyi#ammonite-shell_2.11;0.4.6!ammonite-shell_2.11.jar:

      http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.11/0.4.6/ammonite-shell_2.11-0.4.6.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] (run-main-0) java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:122)
    at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:240)
    at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:237)
    at ammonite.repl.Res$Success.map(Util.scala:27)
    at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:237)
    at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:121)
    at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:108)
    at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:320)
    at ammonite.repl.Repl.<init>(Repl.scala:26)
    at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:166)
    at ammonite.repl.Repl$.repl$1(Repl.scala:166)
    at ammonite.repl.Repl$.run(Repl.scala:174)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.repl.Repl$.main(Repl.scala:142)
    at ammonite.repl.Repl.main(Repl.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
Caused by: java.lang.ExceptionInInitializerError
    at cache502c3e4215029915b5b12a68f6bc9652.$main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:122)
    at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:240)
    at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:237)
    at ammonite.repl.Res$Success.map(Util.scala:27)
    at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:237)
    at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:121)
    at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:108)
    at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:320)
    at ammonite.repl.Repl.<init>(Repl.scala:26)
    at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:166)
    at ammonite.repl.Repl$.repl$1(Repl.scala:166)
    at ammonite.repl.Repl$.run(Repl.scala:174)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.repl.Repl$.main(Repl.scala:142)
    at ammonite.repl.Repl.main(Repl.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
Caused by: ammonite.repl.IvyThing$IvyResolutionException: failed to resolve ivy dependencies com.lihaoyi#ammonite-shell_2.11;0.4.6
    at ammonite.repl.IvyThing$.resolveArtifact(IvyThing.scala:116)
    at ammonite.repl.interp.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:162)
    at cache502c3e4215029915b5b12a68f6bc9652$$anonfun$1.apply$mcV$sp(Main.scala:43)
    at cache502c3e4215029915b5b12a68f6bc9652$.<init>(Main.scala:44)
    at cache502c3e4215029915b5b12a68f6bc9652$.<clinit>(Main.scala)
    at cache502c3e4215029915b5b12a68f6bc9652.$main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:122)
    at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:240)
    at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:237)
    at ammonite.repl.Res$Success.map(Util.scala:27)
    at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:237)
    at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:121)
    at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:108)
    at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:84)
    at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:320)
    at ammonite.repl.Repl.<init>(Repl.scala:26)
    at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:166)
    at ammonite.repl.Repl$.repl$1(Repl.scala:166)
    at ammonite.repl.Repl$.run(Repl.scala:174)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.repl.Repl$.main(Repl.scala:142)
    at ammonite.repl.Repl.main(Repl.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
[trace] Stack trace suppressed: run last writr/ammonite:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last writr/ammonite:run for the full output.
[error] (writr/ammonite:run) Nonzero exit code: 1
[error] Total time: 13 s, completed Dec 8, 2015 8:10:14 AM
```

**Comment by chernetsov** [comment]
as a workaround using 0.1.1-SNAPSHOT helps

```
addSbtPlugin("com.github.alexarchambault" %% "sbt-ammonite" % "0.1.1-SNAPSHOT")
```
